(define (f n m i j cnt)
  (if (= i (+ n 1))
    cnt
    (if (= j (+ n 1))
      (f n m (+ i 1) 1 cnt)
      (let ((k (- m (+ i j))))
        #;(display k)
        #;(newline)
        (if (and (<= 1 k) (<= k n))
          (f n m i (+ j 1) (+ cnt 1))
          (f n m i (+ j 1) cnt)
        )
      )
    )
  )
)

(let ([N (read)][M (read)])
  (display (f N M 1 1 0))
)
